### ISSUE TITLE
Missing class "form-horizontal" makes controls stack

### ISSUE THREAD

**Issue by enkelmedia** [nul800sebastiaan/Cultiv.Tabify#10]
I've noticed that the properties got stacked like this:

![no form](https://user-images.githubusercontent.com/1782524/61571836-f55f7180-aa96-11e9-9913-c6276ee73931.PNG)

Turns out that the wrapping div need a class "form-horizontal" that would fix this.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/nul800sebastiaan/Cultiv.Tabify/issues/10
