### ISSUE TITLE
"Content" dropdown still active, confuses some users because it doesn't work

### ISSUE THREAD

**Issue by MarcStoecker** [nul800sebastiaan/Cultiv.Tabify#12]
The dropdown with the (former) sections is still showing but not switching the tabs.
![image](https://user-images.githubusercontent.com/1537988/63160697-b0d7df00-c01e-11e9-8604-abbf64084037.png)

This is confusing users IMHO as they expect the tabs to switch if they click on a item in this menu?

The dropdown can be hidden with a simple CSS selector. So far I haven't seen any negative side effects.

**Comment by Hendy** [comment]
Hi, this works great for the regular view, but in narrow view, the page sections are rendered as a child of another button:
![TabsNarowViewError](https://user-images.githubusercontent.com/77045/65695923-4b8cfa00-e070-11e9-8898-a469d749ab65.PNG)

**Comment by MarcStoecker** [comment]
Ouch. So much for the QA. 😬 I'll have a look, thanks!

**Comment by MarcStoecker** [comment]
Hey @Hendy, thanks for reporting this. I can't seem to reproduce it with my test instance on 8.1.5.
![image](https://user-images.githubusercontent.com/1537988/65964596-95555600-e45d-11e9-9b34-c7aa942ce0b0.png)

Could you maybe post exact steps or windows sizes and browser or such? No idea right now ... 😕🤔

**Comment by craigs100** [comment]
Hi,

The native V8 "Content" Conte(n||x)t App tab is still visible with package V1.04 and Umb V8.3.0.  Looking at the package source, this section no longer works:-

```
/* hide the "Content" dropdown (avoid confusion) */
.dropdown-menu.umb-sub-views-nav-item__anchor_dropdown.ng-scope {
    display:none;
}
```

I can't see a way of targeting it either or I'd have put a PR in. Hopefully someone can ;)

**Comment by skttl** [comment]
Try removing the `.ng-scope` part from the selector

**Comment by nul800sebastiaan** [comment]
I don't have this problem in 8.3.0.. not sure what I'm doing differently?

![12](https://user-images.githubusercontent.com/304656/70058384-186e6600-15df-11ea-84b2-a9353ff98b19.gif)

**Comment by nul800sebastiaan** [comment]
Is this still a problem in v1.0.5 on Umbraco 8.3.0? I removed the `.ng-scope` part like @skttl suggested. Didn't make a difference for me as this already worked for me but it might help for others?

**Comment by nul800sebastiaan** [comment]
Thanks for reporting this! I have just retired this package since there's something better out there! 👍

Mister Søren Kottal has made many improvements on this package and it's time for me to retire this one! 🎉 If this is still an issue then make sure to head over to https://github.com/skttl/our-umbraco-matryoshka instead.
