### ISSUE TITLE
Grid "Reorder" covers TabList on scroll

### ISSUE THREAD

**Issue by craigs100** [nul800sebastiaan/Cultiv.Tabify#18]
The TablsList is being hidden by the "Reorder" div that jumps up to the top of the editing panel when grids scroll.

Before scroll:
![image](https://user-images.githubusercontent.com/1143883/69975499-3d030900-151f-11ea-8c23-d642f9d9e555.png)

During scroll:
![image](https://user-images.githubusercontent.com/1143883/69975560-5ad06e00-151f-11ea-8187-da8cde86df25.png)

In dev tools setting the tabsList z-index to 100 allows the tabs to show, but using the following CSS fails:
#tabsList {
    z-index: 100 !important;
}

The TabsList div obscuring the "Reorder" div:
![image](https://user-images.githubusercontent.com/1143883/69976102-56588500-1520-11ea-80d5-166a5c264633.png)

Hope fully this can be fixed then this package can be the "must have" solution to fix the inexplicable content navigation UI regression that arrived with all the V8 goodies ;)

**Comment by skttl** [comment]
If you can live with the reorder bar not being sticky, you can slap this CSS in somewhere:

```
#umb-grid > .umb-editor-sub-header[umb-sticky-bar] {
    position: relative;
    z-index: auto;
}
```

**Comment by nul800sebastiaan** [comment]
This is even nicer: 

```
#umb-grid > .umb-editor-sub-header[umb-sticky-bar] { 
	top: 64px;
}
```

Looks like: 

![image](https://user-images.githubusercontent.com/304656/70058564-73a05880-15df-11ea-9a2c-7a9565222522.png)


Although the tab bar should probably have a higher z-index else you'll see it peeking out:

![image](https://user-images.githubusercontent.com/304656/70059146-8b2c1100-15e0-11ea-856b-b9b308c5ce56.png)

This seems to help:

``` 
.fake-top-background, #tabsList {
    z-index: 99;
}
```

And it also allows for "Content / Info" buttons to still show up: 

![image](https://user-images.githubusercontent.com/304656/70059250-bd3d7300-15e0-11ea-94e1-76140930b010.png)

**Comment by nul800sebastiaan** [comment]
v1.0.5 is now available which should fix this issue. https://our.umbraco.com/packages/backoffice-extensions/cultiv-tabify-umbraco-8/

**Comment by craigs100** [comment]
Only now had a chance to test this. Perfect :)  I even like the way it plays with viewlists. Thanks. Now to get it into Core ;)
