### ISSUE TITLE
Feature: Have multiple groups in one tab

### ISSUE THREAD

**Issue by skttl** [nul800sebastiaan/Cultiv.Tabify#2]
This package could be useful :)

I think the groups are good, but still miss my tabs for some things.

I usually have some properties added to almost all nodes (meta info, navigation/search hide togglers, fields for adding extra html/scripts etc.). These would be great to be able to hide away in another tab. But for content stuff, I'm fine with having all that divided into groups in one tab.

So my suggestion would be to have some kind of "tab" setting on each group (just a simple string). Like this:
![billede](https://user-images.githubusercontent.com/3726467/60863656-b3763600-a221-11e9-95e1-1ff6f9b86014.png)

I guess this is not something that is easily stored on the doctype it self. I have not yet played with the new package settings feature, maybe it can be saved there? Or have a config file on disk.

When you load the content editor, you then split each group into the available tabs, and show them. By default there should be a "content" tab for alle groups not assigned to a tab. And if you only have groups from one tab (or no tabs at all) the tab navigation should be invisible.

That way, you can use tabs where it makes sense, and still be able to divide properties into groups.

**Comment by nul800sebastiaan** [comment]
Wow.. that is a very specific request that I can imagine works in your situation but I can't imagine most people have this challenge. I encourage you to clone this project and play with it, feel free to release something new based on this idea!

This is not something I'd like to add to this package though. :-)
