### ISSUE TITLE
Member Properties

### ISSUE THREAD

**Issue by RyanHelmn** [nul800sebastiaan/Cultiv.Tabify#20]
First of all, amazing addition to Umbraco!

Noticed an issue with member properties, running Umbraco 8.5.2. I'd imagine it'd be similar issue with all Umbraco 8 versions?

**Edit**
Is it possible to exclude the members from the interceptor? Or just as simply copy the functionality from the users area? If so, could you point me in the right direction and I could take a look if you're busy!

Full page screenshot attached
![screencapture-localhost-44304-umbraco-2020-01-24-10_12_46](https://user-images.githubusercontent.com/44208607/73061473-27142380-3e92-11ea-85b8-3b2c7a9c5989.png)

**Comment by erikjanwestendorp** [comment]
@Ryyyyannnn Changing the interceptor will probably not solve this issue see description in [PR](https://github.com/nul800sebastiaan/Cultiv.Tabify/pull/21).  @nul800sebastiaan Can you give it a review and if necessary some feedback :-)

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Another solution is to work with tabs in the member sections as well, but I don't know if this is desirable?

**Comment by tompipe** [comment]
Content app for members is being enabled in v8.6 https://github.com/umbraco/Umbraco-CMS/pull/6670 - I've just made PR #22 that helps with introducing tabs into other apps,

**Comment by nul800sebastiaan** [comment]
Thanks for reporting this! I have just retired this package since there's something better out there! 👍

Mister Søren Kottal has made many improvements on this package and it's time for me to retire this one! 🎉 If this is still an issue then make sure to head over to https://github.com/skttl/our-umbraco-matryoshka instead.
