### ISSUE TITLE
Update UI to align more with Umbraco

### ISSUE THREAD

**Issue by FransdeJong** [nul800sebastiaan/Cultiv.Tabify#3]
On twitter there have been some ideas on improving the UI of this package
https://twitter.com/cultiv/status/1147788199361765377

Personaly I like the style Matt proposed:
https://twitter.com/mattbrailsford/status/1148166359588777986

I'd like to discuss the layout here so we can start on getting this package more aligned with the rest of the backoffice.

**Comment by nul800sebastiaan** [comment]
Just go for it, I'm not a designer, Matt is, so trust his judgment. 😅

**Comment by FransdeJong** [comment]
Just making sure we are all on the same page ;-)

**Comment by dalyUSN** [comment]
Hey. I already made a PR for an update to the UI. You can see it here: https://github.com/nul800sebastiaan/Cultiv.Tabify/pull/1

Happy to help you out further.

Thanks
Paul

**Comment by FransdeJong** [comment]
Looks nice!

**Comment by erikjanwestendorp** [comment]
Hi, 

I'm also not a designer but I like the style proposed by Matt as well. Maybe the background color should be white to be more consistent with other sections like settings? See options below.

![option1](https://user-images.githubusercontent.com/7831614/60884179-93a83780-a24c-11e9-8d1b-15006146426b.PNG)

![option2](https://user-images.githubusercontent.com/7831614/60884189-9c990900-a24c-11e9-8a9c-95ad34e0fcfc.PNG)

**Comment by FransdeJong** [comment]
I think the solution of @dalyUSN  is best of both worlds?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/nul800sebastiaan/Cultiv.Tabify/pull/1
