### ISSUE TITLE
Doesn't work when there's validation errors on a different tab

### ISSUE THREAD

**Issue by nul800sebastiaan** [nul800sebastiaan/Cultiv.Tabify#5]
I had a validation error on a different tab then I was on, and I only noticed I couldn't publish but the tab with the error didn't light up so it was very difficult to understand what was going on.

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Do you have wishes or ideas for a solution? My suggestion is to do something like the image below, but maybe it's not clear enough?

![image](https://user-images.githubusercontent.com/7831614/61224563-1898c280-a71f-11e9-9e0b-633ee6c540cf.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/nul800sebastiaan/Cultiv.Tabify/issues/5
